-- 코드를 입력하세요
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM((B.PRICE * BS.SALES)) AS SALES
FROM AUTHOR A, (BOOK_SALES BS INNER JOIN BOOK B
ON BS.BOOK_ID = B.BOOK_ID) 
WHERE YEAR(SALES_DATE)='2022' AND MONTH(SALES_DATE)='01' AND B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY AUTHOR_ID,CATEGORY
ORDER BY AUTHOR_ID ASC, B.CATEGORY DESC