-- 코드를 입력하세요
# SELECT I.REST_ID,I.REST_NAME, I.FOOD_TYPE,I.FAVORITES,I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE),2) AS SCORE
# FROM REST_INFO AS I, REST_REVIEW AS R
# WHERE I.REST_ID = R.REST_ID AND I.ADDRESS LIKE ('서울특별시%')
# ORDER BY SCORE DESC, I.FAVORITES DESC;

SELECT A.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) SCORE 
FROM REST_INFO A RIGHT JOIN REST_REVIEW B
ON A.REST_ID = B.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY A.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC